### PR TITLE
Update supabase config.toml and readme

### PR DESCRIPTION
**Pull request by alexpaden**
Not sure if the .toml was modified originally to remove schemas, but the major_version needed to be changed to deploy

### CODE REVIEW

**Comment by gskril** [comment]
Thanks @alexpaden! I think I just used the default config.toml file but know Supabase recently pushed a major update so the version change makes sense.

Is there a reason for specifying `[storage]` and `[schemas]`, and changing the supabase link CLI command? Or are those just new defaults as well?

**Comment by alexpaden** [comment]
Sure thing @gskril

I couldn't locate any information on the supabase CLI command **supabase db remote set**; the only available command for **supabase db remote** is **commit**. So I don't know if that was part of the update.

image

The docs suggest **supabase login** and **supabase link --project ref [proj_ref]**

The config.toml file is the new default generated.

**Comment by alexpaden** [comment]
It looks like they scrubbed the page with **supabase db remote set**. I believe said commands are the new default.

**Comment by alexpaden** [comment]
I think these are right, but I'm going to close it because it was messy & I messed up that readme merge 👍

**Pull request closed without merging**
